language: node_js
os: linux
dist: xenial
node_js:
  - "10"

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm run lint-contracts
  - npm run prettier-check
  - npm run coverage

after_script:
  - cat coverage/lcov.info | coveralls