language: node_js
os: linux
dist: xenial
node_js:
  - "10"

cache:
  directories:
  - node_modules

before_install:
  - export NODE_OPTIONS=--max_old_space_size=6144

install:
  - npm ci

script:
  - npm run coverage

after_script:
  - cat coverage/lcov.info | coveralls